org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.223
neo_version_range=[21.1.0,)
loader_version_range=[1,)
mod_id=tetra
mod_name=tetra
mod_license=ARR
mod_version=6.13.0
mod_group_id=se.mickelus.tetra
mod_authors=Mickelus
mod_description=Tetra revolves around modular items and attempts to blend it together with other concepts such as adventure and technology.
mutil_version=1.21.1-6.3.1
mutil_version_range=[6.3.1,]
curios_version=9.5.1+1.21.1
curios_version_range=[9.5.1+1.21.1,]
