modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mutil"
type="required"
versionRange="${mutil_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="${curios_version_range}"
ordering="NONE"
side="BOTH"
